from typing import Any

class Figure:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_trace(self, trace: Any, *args: Any, **kwargs: Any) -> "Figure": ...
    def update_layout(self, *args: Any, **kwargs: Any) -> None: ...
    def write_html(self, file: Any, *args: Any, **kwargs: Any) -> None: ...
    def write_image(self, file: Any, *args: Any, **kwargs: Any) -> None: ...

class Surface:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
