"""Minimal stubs for `matplotlib.axes` to reduce Pylance/pyright noise.

This file provides pragmatic, permissive signatures for a handful of
commonly-used `Axes` members (including `clear`) so callers in the
repository don't propagate "partially unknown" diagnostics.
"""

from typing import Any, Dict, List, Tuple, Sequence
from numpy.typing import NDArray, ArrayLike

# Minimal forward declarations for common Matplotlib types used by the project
class Colormap: ...
class Normalize: ...
class AxesImage: ...
class BarContainer: ...
class Text: ...
class Legend: ...
class Tick: ...
class Colorbar: ...
class Artist: ...
class QuadContourSet: ...

class Axes:
    """Pragmatic Axes stub with a small surface area used by the project.

    Methods intentionally accept/return `Any` or simple forward-declared
    types to avoid propagating unknown types from matplotlib into the
    codebase while keeping runtime behavior unchanged.
    """

    def clear(self) -> None: ...
    def imshow(self, X: ArrayLike, *args: Any, **kwargs: Any) -> AxesImage: ...
    def contour(self, X: ArrayLike, *args: Any, **kwargs: Any) -> QuadContourSet: ...
    def colorbar(self, mappable: Any = ..., *args: Any, **kwargs: Any) -> Colorbar: ...
    def legend(
        self,
        handles: Any | None = ...,
        labels: Any | None = ...,
        *args: Any,
        **kwargs: Any,
    ) -> Legend: ...
    def add_subplot(self, *args: Any, **kwargs: Any) -> "Axes": ...
    def set_title(self, title: str, *args: Any, **kwargs: Any) -> Text: ...
    def set_xlabel(self, xlabel: str, *args: Any, **kwargs: Any) -> Text: ...
    def set_ylabel(self, ylabel: str, *args: Any, **kwargs: Any) -> Text: ...
    def set_xticks(
        self, ticks: Sequence[float], *args: Any, **kwargs: Any
    ) -> List[Tick]: ...
    def set_xticklabels(
        self, labels: Sequence[str], *args: Any, **kwargs: Any
    ) -> List[Text]: ...
    def set_yticks(
        self, ticks: Sequence[float], *args: Any, **kwargs: Any
    ) -> List[Tick]: ...
    def set_yticklabels(
        self, labels: Sequence[str], *args: Any, **kwargs: Any
    ) -> List[Text]: ...
    def text(self, *args: Any, **kwargs: Any) -> Text: ...
    def grid(self, *args: Any, **kwargs: Any) -> None: ...
    def hist(
        self, x: ArrayLike, *args: Any, **kwargs: Any
    ) -> Tuple[NDArray[Any], NDArray[Any], Any]: ...
    def boxplot(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...
    def bar(self, *args: Any, **kwargs: Any) -> BarContainer: ...
    def get_legend_handles_labels(self) -> Tuple[List[Artist], List[str]]: ...

    # Accept generic attribute access for very dynamic uses in codebase
    def __getattr__(self, name: str) -> Any: ...
