from typing import Any

# Re-export the canonical Axes type from `matplotlib.axes` so callers that
# annotate `matplotlib.figure.Axes` are compatible with `matplotlib.axes.Axes`.
from matplotlib.axes import Axes

from .colorbar import Colorbar

class SubplotSpec: ...
class Text: ...
class AxesImage: ...

class Figure:
    def add_subplot(self, *args: Any, **kwargs: Any) -> Axes: ...
    def suptitle(self, *args: Any, **kwargs: Any) -> Text: ...
    def savefig(self, *args: Any, **kwargs: Any) -> None: ...
    def add_trace(self, *args: Any, **kwargs: Any) -> Any: ...
    def subplots(self, *args: Any, **kwargs: Any) -> tuple["Figure", Axes]: ...
    def colorbar(self, *args: Any, **kwargs: Any) -> Colorbar: ...
    def tight_layout(self, *args: Any, **kwargs: Any) -> None: ...

def subplots(*args: Any, **kwargs: Any) -> tuple[Figure, Axes]: ...
