from typing import Any

class Axes3D:
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...
    def scatter(self, *args: Any, **kwargs: Any) -> Any: ...
    def plot_surface(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_xlabel(self, label: Any) -> None: ...
    def set_ylabel(self, label: Any) -> None: ...
    def set_zlabel(self, label: Any) -> None: ...

class art3d: ...

__all__ = ["Axes3D", "art3d"]
