"""Type stubs for `mpl_toolkits.mplot3d.axes3d` used by the project.

These are minimal, intentionally small stubs to satisfy type-checking in
the repository. They are not exhaustive implementations of Matplotlib.
"""

from typing import Any, Iterable

class Axes3D:
    def add_collection3d(self, col: Any) -> None: ...
    def scatter(self, *args: Any, **kwargs: Any) -> Any: ...
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...
    def plot_surface(self, *args: Any, **kwargs: Any) -> Any: ...
    def auto_scale_xyz(
        self, xs: Iterable[float], ys: Iterable[float], zs: Iterable[float]
    ) -> None: ...
    def set_xlabel(self, label: Any) -> None: ...
    def set_ylabel(self, label: Any) -> None: ...
    def set_zlabel(self, label: Any) -> None: ...
    def set_xlim(self, left: float, right: float) -> None: ...
    def set_ylim(self, bottom: float, top: float) -> None: ...
    def set_zlim(self, bottom: float, top: float) -> None: ...
    def get_xticks(self) -> list[float]: ...
    def set_xticklabels(self, labels: Iterable[str]) -> None: ...
    def get_yticks(self) -> list[float]: ...
    def set_yticklabels(self, labels: Iterable[str]) -> None: ...
    def view_init(
        self,
        elev: float | None = None,
        azim: float | None = None,
        roll: float | None = None,
    ) -> None: ...
    def get_proj(self) -> Any: ...
    def get_figure(self) -> Any: ...

__all__ = ["Axes3D"]
