from typing import Any, Callable, TypeVar, overload
from typing_extensions import ParamSpec

P = ParamSpec("P")
R = TypeVar("R")

@overload
def njit(func: Callable[P, R]) -> Callable[P, R]: ...
@overload
def njit(
    *, cache: Any = ..., parallel: Any = ..., nogil: Any = ..., fastmath: Any = ...
) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
@overload
def njit(arg: Any) -> Callable[[Callable[P, R]], Callable[P, R]]: ...

# Fallback implementation signature for tools that don't use overload resolution.
def njit(*args: Any, **kwargs: Any) -> Any: ...
def prange(*args: Any, **kwargs: Any) -> Any: ...
def typeof(obj: Any) -> Any: ...

__all__ = ["njit", "prange", "typeof"]
